"""Add securities table

Revision ID: 774e33f26820
Revises: 78b2ed929b9b
Create Date: 2019-10-09 14:39:54.762472

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "774e33f26820"
down_revision = "78b2ed929b9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "securities",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.add_column(
        "buy_orders", sa.Column("security_id", postgresql.UUID(), nullable=False)
    )
    op.create_foreign_key(None, "buy_orders", "securities", ["security_id"], ["id"])
    op.add_column(
        "sell_orders", sa.Column("security_id", postgresql.UUID(), nullable=False)
    )
    op.create_foreign_key(None, "sell_orders", "securities", ["security_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sell_orders", type_="foreignkey")
    op.drop_column("sell_orders", "security_id")
    op.drop_constraint(None, "buy_orders", type_="foreignkey")
    op.drop_column("buy_orders", "security_id")
    op.drop_table("securities")
    # ### end Alembic commands ###
