"""create colume chat_room

Revision ID: d87206c0b468
Revises: cd06c645f572
Create Date: 2019-11-03 14:46:11.852815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd87206c0b468'
down_revision = 'cd06c645f572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('is_deal_closed', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'is_deal_closed')
    # ### end Alembic commands ###
