"""Add timezones to datetime

Revision ID: 9b9b1a14c365
Revises: 04be10e1f89a
Create Date: 2019-10-07 09:37:46.416835

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "9b9b1a14c365"
down_revision = "04be10e1f89a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for tbl in ["sellers", "buyers", "sell_orders", "buy_orders", "invites", "matches"]:
        for col in ["created_at", "updated_at"]:
            op.alter_column(tbl, col, type_=postgresql.TIMESTAMP(timezone=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    for tbl in ["sellers", "buyers", "sell_orders", "buy_orders", "invites", "matches"]:
        for col in ["created_at", "updated_at"]:
            op.alter_column(tbl, col, type_=postgresql.TIMESTAMP(timezone=False))
    # ### end Alembic commands ###
