"""is rejected

Revision ID: 5e654a78d4b0
Revises: 900ef5dcc94d
Create Date: 2019-11-02 17:45:05.392315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e654a78d4b0'
down_revision = '900ef5dcc94d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
