"""is rejected

Revision ID: 900ef5dcc94d
Revises: 949af0f151f9
Create Date: 2019-11-02 17:44:46.334407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900ef5dcc94d'
down_revision = '949af0f151f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('is_rejected', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'is_rejected')
    # ### end Alembic commands ###
