"""Add full name to seller

Revision ID: 78b2ed929b9b
Revises: 9b9b1a14c365
Create Date: 2019-10-07 22:44:52.210550

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "78b2ed929b9b"
down_revision = "9b9b1a14c365"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sellers",
        sa.Column("full_name", sa.String(), nullable=False, server_default="Unknown"),
    )
    op.alter_column("sellers", "full_name", server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sellers", "full_name")
    # ### end Alembic commands ###
