"""Add rounds

Revision ID: ff31f1d3c98d
Revises: 28f0b17593fb
Create Date: 2019-10-15 17:21:23.939060

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "ff31f1d3c98d"
down_revision = "28f0b17593fb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rounds",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_concluded", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("buy_orders", sa.Column("round_id", postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, "buy_orders", "rounds", ["round_id"], ["id"])
    op.add_column(
        "sell_orders", sa.Column("round_id", postgresql.UUID(), nullable=True)
    )
    op.create_foreign_key(None, "sell_orders", "rounds", ["round_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sell_orders", type_="foreignkey")
    op.drop_column("sell_orders", "round_id")
    op.drop_constraint(None, "buy_orders", type_="foreignkey")
    op.drop_column("buy_orders", "round_id")
    op.drop_table("rounds")
    # ### end Alembic commands ###
