"""add enum

Revision ID: cd06c645f572
Revises: 33a3423b63e1
Create Date: 2019-11-03 14:18:17.560028

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "cd06c645f572"
down_revision = "33a3423b63e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    offer_status = postgresql.ENUM(
        "ACCEPTED", "REJECTED", "PENDING", name="offer_statuses"
    )
    offer_status.create(op.get_bind())
    op.add_column(
        "offers",
        sa.Column(
            "offer_status",
            sa.Enum("ACCEPTED", "REJECTED", "PENDING", name="offer_statuses"),
            nullable=False,
            server_default="PENDING",
        ),
    )
    op.drop_column("offers", "is_rejected")
    op.drop_column("offers", "is_agreeable")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "offers",
        sa.Column(
            "is_agreeable",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "offers",
        sa.Column(
            "is_rejected",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("offers", "offer_status")
    offer_status = postgresql.ENUM(
        "ACCEPTED", "REJECTED", "PENDING", name="offer_status"
    )
    offer_status.drop(op.get_bind())
    # ### end Alembic commands ###
