"""Add unique pair constraint on banned pairs

Revision ID: 05c8727bad8b
Revises: 790d9ba4e3f6
Create Date: 2019-10-21 08:15:47.728942

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "05c8727bad8b"
down_revision = "790d9ba4e3f6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "banned_pairs", ["buyer_id", "seller_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "banned_pairs", type_="unique")
    # ### end Alembic commands ###
