"""add anonymous id

Revision ID: ec6e08f4046c
Revises: d87206c0b468
Create Date: 2019-11-03 23:15:59.241393

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec6e08f4046c'
down_revision = 'd87206c0b468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('buyer_hidden_id', postgresql.UUID(), nullable=False))
    op.add_column('chat_rooms', sa.Column('seller_hidden_id', postgresql.UUID(), nullable=False))
    op.add_column('chats', sa.Column('author_hidden_id', postgresql.UUID(), nullable=False))
    op.add_column('offers', sa.Column('author_hidden_id', postgresql.UUID(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'author_hidden_id')
    op.drop_column('chats', 'author_hidden_id')
    op.drop_column('chat_rooms', 'seller_hidden_id')
    op.drop_column('chat_rooms', 'buyer_hidden_id')
    # ### end Alembic commands ###
