"""Add users is_committee column

Revision ID: ef91f854aca4
Revises: 05c8727bad8b
Create Date: 2019-10-21 13:20:59.621367

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "ef91f854aca4"
down_revision = "05c8727bad8b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_committee", sa.Boolean(), server_default="t", nullable=False),
    )
    op.alter_column("users", "can_buy", server_default="t")
    op.alter_column("users", "can_sell", server_default="t")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_committee")
    op.alter_column("users", "can_buy", server_default=None)
    op.alter_column("users", "can_sell", server_default=None)
    # ### end Alembic commands ###
