"""Add market_price to security

Revision ID: 593c10ebcda7
Revises: 26e119aa2784
Create Date: 2019-10-29 16:34:24.013281

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "593c10ebcda7"
down_revision = "26e119aa2784"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("securities", sa.Column("market_price", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("securities", "market_price")
    # ### end Alembic commands ###
