"""Change for 4 Nov

Revision ID: 85b11b1c3975
Revises: d87206c0b468
Create Date: 2019-11-04 13:08:48.634404

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "85b11b1c3975"
down_revision = "d87206c0b468"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_requests",
        sa.Column("closed_by_user_id", postgresql.UUID(), nullable=True),
    )
    op.create_foreign_key(None, "user_requests", "users", ["closed_by_user_id"], ["id"])
    op.add_column("users", sa.Column("auth_token", sa.String(), nullable=True))
    op.alter_column("users", "user_id", new_column_name="provider_user_id")
    op.drop_constraint("users_user_id_key", "users", type_="unique")
    op.create_unique_constraint(None, "users", ["provider_user_id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "provider_user_id", new_column_name="user_id")
    op.drop_constraint(None, "users", type_="unique")
    op.create_unique_constraint("users_user_id_key", "users", ["user_id"])
    op.drop_column("users", "auth_token")
    op.drop_constraint(None, "user_requests", type_="foreignkey")
    op.drop_column("user_requests", "closed_by_user_id")
    # ### end Alembic commands ###
