"""Add is_revealed to ChatRoom

Revision ID: 26e119aa2784
Revises: fd046a5efd55
Create Date: 2019-10-28 16:33:51.696604

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "26e119aa2784"
down_revision = "fd046a5efd55"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_rooms",
        sa.Column("is_revealed", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_rooms", "is_revealed")
    # ### end Alembic commands ###
