"""Remove invites

Revision ID: 28f0b17593fb
Revises: 820edc601f67
Create Date: 2019-10-10 12:53:04.094224

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "28f0b17593fb"
down_revision = "820edc601f67"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sell_invites")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sell_invites",
        sa.Column("id", postgresql.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "origin_seller_id", postgresql.UUID(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "destination_email", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("valid", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "expiry_time",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["origin_seller_id"],
            ["users.id"],
            name="sell_invites_origin_seller_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="sell_invites_pkey"),
    )
    # ### end Alembic commands ###
